# Generated by Django 5.1.8 on 2025-06-24 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_services', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityservice',
            name='specialists',
            field=models.ManyToManyField(blank=True, related_name='facility_services', to='staff.medicalspecialist', verbose_name='Специалисты'),
        ),
        migrations.AddField(
            model_name='facilityservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='medical_services.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='medical_services.servicecategory', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(related_name='services', to='medical_services.servicecategory', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='facility_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='medical_services.facilityservice', verbose_name='Услуга учреждения'),
        ),
        migrations.AlterUniqueTogether(
            name='facilityservice',
            unique_together={('content_type', 'object_id', 'service')},
        ),
    ]
