# Generated by Django 5.1.8 on 2025-07-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_services', '0003_alter_service_slug_alter_servicecategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='display_priority',
            field=models.IntegerField(choices=[(3, 'Высокий'), (2, 'Средний'), (1, 'Низкий')], default=2, help_text='Высокий — 3, Средний — 2, Низкий — 1', verbose_name='Приоритет отображения'),
        ),
    ]
