# Generated by Django 5.1.8 on 2025-07-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_services', '0004_service_display_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
    ]
