# Generated by Django 5.1.8 on 2025-07-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_services', '0005_remove_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_rehabilitation_program',
            field=models.BooleanField(default=False, help_text='Отметьте, если услуга является реабилитационной программой', verbose_name='Реабилитационная программа'),
        ),
    ]
