# Generated by Django 5.1.8 on 2025-07-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_services', '0006_service_is_rehabilitation_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='therapymethod',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='therapymethod',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title'),
        ),
    ]
