# Generated by Django 5.1.11 on 2025-07-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_services', '0007_service_meta_description_service_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='display_priority',
        ),
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше услуга в списке. 0 - в конце списка.', verbose_name='Порядок отображения'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['display_order', 'is_active'], name='medical_ser_display_cd8199_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'display_order'], name='medical_ser_is_acti_73ff3c_idx'),
        ),
    ]
