services:
  web:
    build: .
    image: web:1.0.0
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - .:/usr/src/project_rehabs_platform
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:16-bookworm
    container_name: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=platform
  dbbrowser:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
