# Generated by Django 5.1.11 on 2025-07-28 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='core.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Координаты города',
                'verbose_name_plural': 'Координаты городов',
                'ordering': ['city__name'],
                'unique_together': {('city',)},
            },
        ),
    ]
