# Generated by Django 5.1.11 on 2025-08-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('experience_years', models.IntegerField(verbose_name='Стаж (лет)')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Образование')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='О специалисте')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Достижения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='specialists/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Медицинский специалист',
                'verbose_name_plural': 'Медицинские специалисты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('document_type', models.CharField(choices=[('diploma', 'Диплом'), ('certificate', 'Сертификат'), ('license', 'Лицензия'), ('specialization', 'Специализация'), ('other', 'Другое')], max_length=20, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('document', models.FileField(upload_to='specialists/documents/', verbose_name='Документ')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер документа')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staff.medicalspecialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Документ специалиста',
                'verbose_name_plural': 'Документы специалистов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='medicalspecialist',
            name='specializations',
            field=models.ManyToManyField(to='staff.specialization', verbose_name='Специализации'),
        ),
        migrations.CreateModel(
            name='FacilitySpecialist',
            fields=[
                ('medicalspecialist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='staff.medicalspecialist')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('schedule', models.TextField(blank=True, null=True, verbose_name='График работы')),
                ('order', models.PositiveIntegerField(blank=True, default=None, help_text='Меньшее значение — выше в списке. Если не указано, специалист отображается после приоритетных.', null=True, verbose_name='Порядок отображения')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Keywords')),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='staff/meta_images/', verbose_name='Meta Image (OG/Twitter)')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
            ],
            options={
                'verbose_name': 'Специалист учреждения',
                'verbose_name_plural': 'Специалисты учреждений',
            },
            bases=('staff.medicalspecialist',),
        ),
    ]
