# Generated by Django 5.1.8 on 2025-04-22 14:08

from django.db import migrations
from django.utils.text import slugify

def update_specialist_slugs(apps, schema_editor):
    FacilitySpecialist = apps.get_model('staff', 'FacilitySpecialist')
    
    for specialist in FacilitySpecialist.objects.all():
        # Формируем базовый слаг из фамилии и имени
        base_slug = slugify(f"{specialist.last_name}-{specialist.first_name}")
        if not base_slug:  # Если после slugify получили пустую строку
            base_slug = f"specialist-{specialist.id}"
        slug = base_slug
        
        # Проверяем, существует ли уже такой слаг
        counter = 1
        while FacilitySpecialist.objects.filter(slug=slug).exclude(pk=specialist.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
            
        specialist.slug = slug
        specialist.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_specialist_slugs),
    ]
