# Generated by Django 5.1.11 on 2025-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityspecialist',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='facilityspecialist',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='staff/meta_images/', verbose_name='Meta Image (OG/Twitter)'),
        ),
        migrations.AddField(
            model_name='facilityspecialist',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='facilityspecialist',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title'),
        ),
    ]
