# Generated by Django 5.1.11 on 2025-07-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_facilityspecialist_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalspecialist',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='Образование'),
        ),
    ]
