# Generated by Django 5.1.11 on 2025-07-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_medicalspecialist_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalspecialist',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='О специалисте'),
        ),
    ]
