# Generated by Django 5.1.11 on 2025-07-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_medicalspecialist_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityspecialist',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Меньшее значение — выше в списке. Если не указано, специалист отображается после приоритетных.', null=True, verbose_name='Порядок отображения'),
        ),
    ]
