# Generated by Django 5.1.8 on 2025-06-24 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание')),
                ('competencies', models.TextField(verbose_name='Ключевые компетенции')),
            ],
            options={
                'verbose_name': 'Тип организации',
                'verbose_name_plural': 'Типы организаций',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('document_type', models.CharField(choices=[('license', 'Лицензия'), ('certificate', 'Сертификат'), ('accreditation', 'Аккредитация'), ('insurance', 'Страховка'), ('other', 'Другое')], max_length=20, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('document', models.FileField(upload_to='facilities/documents/', verbose_name='Документ')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер документа')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
            ],
            options={
                'verbose_name': 'Документ учреждения',
                'verbose_name_plural': 'Документы учреждений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('image', models.ImageField(upload_to='facilities/images/', verbose_name='Изображение')),
                ('image_type', models.CharField(choices=[('main', 'Главное фото'), ('exterior', 'Экстерьер'), ('interior', 'Интерьер'), ('equipment', 'Оборудование'), ('other', 'Другое')], default='main', max_length=50, verbose_name='Тип изображения')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
            ],
            options={
                'verbose_name': 'Изображение учреждения',
                'verbose_name_plural': 'Изображения учреждений',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('address', models.TextField(default='', verbose_name='Адрес')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб-сайт')),
                ('license_number', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Номер лицензии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('emergency_support', models.BooleanField(default=False, verbose_name='Экстренная помощь')),
                ('has_hospital', models.BooleanField(default=False, verbose_name='Стационар')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.city', verbose_name='Город')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.organizationtype', verbose_name='Тип организации')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
            },
        ),
        migrations.CreateModel(
            name='RehabCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб-сайт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('capacity', models.IntegerField(default=0, verbose_name='Вместимость')),
                ('program_duration', models.IntegerField(default=0, verbose_name='Длительность программы (дней)')),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная цена')),
                ('accommodation_conditions', models.TextField(blank=True, default='', null=True, verbose_name='Условия проживания')),
                ('address', models.TextField(default='', verbose_name='Адрес')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.city', verbose_name='Город')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.organizationtype', verbose_name='Тип организации')),
            ],
            options={
                'verbose_name': 'Реабилитационный центр',
                'verbose_name_plural': 'Реабилитационные центры',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('content', models.TextField(verbose_name='Содержание отзыва')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
