# Generated by Django 5.1.11 on 2025-08-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('facilities', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatedoctor',
            name='specializations',
            field=models.ManyToManyField(to='staff.specialization', verbose_name='Специализации'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='organization_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.organizationtype', verbose_name='Тип организации'),
        ),
        migrations.AddField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента'),
        ),
    ]
