# Generated by Django 5.1.8 on 2025-07-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('facilities', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('experience_years', models.IntegerField(verbose_name='Стаж (лет)')),
                ('education', models.TextField(verbose_name='Образование')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Достижения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='private_doctors/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон для записи')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для связи')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Личный сайт')),
                ('address', models.TextField(verbose_name='Адрес приема')),
                ('office_description', models.TextField(blank=True, null=True, verbose_name='Описание кабинета/офиса')),
                ('parking_available', models.BooleanField(default=False, verbose_name='Наличие парковки')),
                ('wheelchair_accessible', models.BooleanField(default=False, verbose_name='Доступность для инвалидных колясок')),
                ('schedule', models.TextField(verbose_name='График работы')),
                ('home_visits', models.BooleanField(default=False, verbose_name='Выезд на дом')),
                ('emergency_available', models.BooleanField(default=False, verbose_name='Экстренная помощь')),
                ('weekend_work', models.BooleanField(default=False, verbose_name='Работа в выходные')),
                ('consultation_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость консультации')),
                ('home_visit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость выезда на дом')),
                ('payment_methods', models.CharField(default='Наличные', help_text='Например: наличные, карта, перевод', max_length=200, verbose_name='Способы оплаты')),
                ('insurance_accepted', models.BooleanField(default=False, verbose_name='Принимает страховку')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер лицензии')),
                ('license_issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи лицензии')),
                ('license_expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок действия лицензии')),
                ('online_consultations', models.BooleanField(default=False, verbose_name='Онлайн консультации')),
                ('video_consultations', models.BooleanField(default=False, verbose_name='Видеоконсультации')),
                ('languages', models.CharField(default='Русский', help_text='Например: русский, английский', max_length=200, verbose_name='Языки общения')),
                ('special_equipment', models.TextField(blank=True, null=True, verbose_name='Специальное оборудование')),
                ('verified', models.BooleanField(default=False, verbose_name='Подтвержденный врач')),
                ('featured', models.BooleanField(default=False, verbose_name='Рекомендуемый врач')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.city', verbose_name='Город')),
                ('specializations', models.ManyToManyField(to='staff.specialization', verbose_name='Специализации')),
            ],
            options={
                'verbose_name': 'Частный врач',
                'verbose_name_plural': 'Частные врачи',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
