# Generated by Django 5.1.8 on 2025-07-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_privatedoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatedoctor',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес приема'),
        ),
        migrations.AlterField(
            model_name='privatedoctor',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='Образование'),
        ),
    ]
