# Generated by Django 5.1.8 on 2025-07-12 13:39

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def add_organization_type_and_name(apps, schema_editor):
    """Добавляем тип организации и название для существующих врачей"""
    PrivateDoctor = apps.get_model('facilities', 'PrivateDoctor')
    OrganizationType = apps.get_model('facilities', 'OrganizationType')
    
    # Получаем или создаем тип организации "Частный врач"
    private_doctor_type, created = OrganizationType.objects.get_or_create(
        slug='private-doctor',
        defaults={
            'name': 'Частный врач',
            'description': 'Частнопрактикующие врачи и медицинские специалисты',
            'competencies': 'Индивидуальные консультации, диагностика, лечение, профилактика'
        }
    )
    
    # Обновляем существующих врачей
    for doctor in PrivateDoctor.objects.all():
        # Формируем название из имени и фамилии
        if doctor.middle_name:
            doctor.name = f"{doctor.last_name} {doctor.first_name} {doctor.middle_name}"
        else:
            doctor.name = f"{doctor.last_name} {doctor.first_name}"
        
        # Устанавливаем тип организации
        doctor.organization_type = private_doctor_type
        
        # Обновляем slug если нужно
        if not doctor.slug:
            base_slug = slugify(f"{doctor.last_name}-{doctor.first_name}")
            slug = base_slug
            counter = 1
            while PrivateDoctor.objects.filter(slug=slug).exclude(id=doctor.id).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            doctor.slug = slug
        
        doctor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('facilities', '0003_alter_privatedoctor_address_and_more'),
    ]

    operations = [
        # Добавляем недостающие поля
        migrations.AddField(
            model_name='privatedoctor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название', default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatedoctor',
            name='organization_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='facilities.organizationtype',
                verbose_name='Тип организации',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='privatedoctor',
            name='description',
            field=models.TextField(verbose_name='Описание', default=''),
        ),
        migrations.AddField(
            model_name='privatedoctor',
            name='license_number',
            field=models.CharField(
                max_length=50,
                verbose_name='Номер лицензии',
                default='',
                blank=True,
                null=True
            ),
        ),
        
        # Обновляем данные
        migrations.RunPython(add_organization_type_and_name),
        
        # Делаем поля обязательными
        migrations.AlterField(
            model_name='privatedoctor',
            name='organization_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='facilities.organizationtype',
                verbose_name='Тип организации'
            ),
        ),
        
        # Удаляем дублирующиеся поля
        migrations.RemoveField(
            model_name='privatedoctor',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='privatedoctor',
            name='featured',
        ),
    ]
