# Generated by Django 5.1.8 on 2025-07-12 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('facilities', '0004_refactor_private_doctor_step1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatedoctor',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='privatedoctor',
            name='payment_methods',
        ),
        migrations.AlterField(
            model_name='privatedoctor',
            name='address',
            field=models.TextField(default='', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='privatedoctor',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='privatedoctor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='privatedoctor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='privatedoctor',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='privatedoctor',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='privatedoctor',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Веб-сайт'),
        ),
    ]
