# Generated by Django 5.1.8 on 2025-07-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_remove_languages_and_payment_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatedoctor',
            name='photo',
        ),
    ]
