# Generated by Django 5.1.8 on 2025-07-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_remove_photo_from_private_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabcenter',
            name='min_price',
            field=models.IntegerField(default=0, verbose_name='Минимальная цена'),
        ),
    ]
