# Generated by Django 5.1.8 on 2025-07-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_alter_rehabcenter_min_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehabcenter',
            name='accommodation_conditions',
        ),
        migrations.RemoveField(
            model_name='rehabcenter',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='rehabcenter',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='rehabcenter',
            name='program_duration',
        ),
    ]
