# Generated by Django 5.1.11 on 2025-07-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_clinic_meta_description_clinic_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='facilities/meta_images/', verbose_name='Meta Image (OG/Twitter)'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='privatedoctor',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='facilities/meta_images/', verbose_name='Meta Image (OG/Twitter)'),
        ),
        migrations.AddField(
            model_name='privatedoctor',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='facilities/meta_images/', verbose_name='Meta Image (OG/Twitter)'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Keywords'),
        ),
    ]
