# Generated by Django 5.1.11 on 2025-07-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0010_clinic_meta_image_clinic_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Отметьте, чтобы показать учреждение на главной странице в приоритетном порядке', verbose_name='Показать на главной странице'),
        ),
        migrations.AddField(
            model_name='privatedoctor',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Отметьте, чтобы показать учреждение на главной странице в приоритетном порядке', verbose_name='Показать на главной странице'),
        ),
        migrations.AddField(
            model_name='rehabcenter',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Отметьте, чтобы показать учреждение на главной странице в приоритетном порядке', verbose_name='Показать на главной странице'),
        ),
    ]
