# Generated by Django 5.1.11 on 2025-07-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0011_clinic_is_featured_privatedoctor_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
