# Generated by Django 5.1.8 on 2025-06-24 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslevel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_levels', to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем'),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='access_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to='admin_logs.accesslevel', verbose_name='Уровень доступа'),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='apppermission',
            name='access_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to='admin_logs.accesslevel', verbose_name='Уровень доступа'),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='access_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='admin_logs.accesslevel', verbose_name='Уровень доступа'),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Назначен пользователем'),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='apppermission',
            unique_together={('app_label', 'access_level')},
        ),
    ]
