# Generated by Django 5.1.8 on 2025-07-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Отображать карточку на главной странице', verbose_name='На главной странице'),
        ),
    ]
