# Generated by Django 5.1.11 on 2025-07-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_recoverystory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/meta_images/', verbose_name='Meta Image (OG/Twitter)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/meta_images/', verbose_name='Meta Image (OG/Twitter)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Keywords'),
        ),
    ]
