"""
Django settings for rehabs_platform project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from  rehabs_platform.secret import MY_SECRET_KEY

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = MY_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'django_cleanup.apps.CleanupConfig',
    
    # Local apps
    'core.apps.CoreConfig',
    'facilities.apps.FacilitiesConfig',
    'staff.apps.StaffConfig',
    'users.apps.UsersConfig',
    'blog.apps.BlogConfig',
    'requests.apps.RequestsConfig',
    'medical_services.apps.MedicalServicesConfig',
    'reviews.apps.ReviewsConfig',
    'recovery_stories.apps.RecoveryStoriesConfig',
    'admin_logs.apps.AdminLogsConfig',
    'content.apps.ContentConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rehabs_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'content.context_processors.site_content',
            ],
        },
    },
]

WSGI_APPLICATION = 'rehabs_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Настройки для системы логирования
ADMIN_LOGS = {
    'ENABLE_LOGGING': True,
    'LOG_IP_ADDRESS': True,
    'LOG_USER_AGENT': True,
    'LOG_ACCESS_LEVEL': True,
    'EXCLUDE_MODELS': [
        'admin_logs.AdminActionLog',
        'auth.Group',
        'auth.Permission',
    ],
    'INCLUDE_MODELS': [
        'blog.*',
        'recovery_stories.*',
        'requests.*',
        'facilities.*',
        'staff.*',
        'content.*',
    ],
}

# Настройки для системы доступа
ACCESS_CONTROL = {
    'DEFAULT_ACCESS_LEVEL': 'content_admin',
    'SUPERUSER_ACCESS_LEVEL': 'superuser',
    'ENABLE_TEMPORARY_ACCESS': True,
    'DEFAULT_ACCESS_DURATION': 30,  # дней
}

# JSON сериализация
DEFAULT_JSON_ENCODER = 'facilities.utils.CustomJSONEncoder'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@rehabs-platform.com'
