# Generated by Django 5.1.11 on 2025-08-02 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('facilities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('request_type', models.CharField(choices=[('consultation', 'Консультация'), ('treatment', 'Лечение'), ('rehabilitation', 'Реабилитация'), ('partner', 'Партнерство'), ('other', 'Другое')], max_length=20, verbose_name='Тип заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('waiting_commission', 'Ожидание комиссии'), ('commission_received', 'Комиссия получена'), ('treatment_started', 'Лечение начато'), ('treatment_completed', 'Лечение завершено'), ('cancelled', 'Отменена'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('source', models.CharField(choices=[('website_form', 'Веб-форма'), ('phone_call', 'Телефонный звонок'), ('email', 'Email'), ('offline', 'Очное обращение'), ('other', 'Другое')], default='website_form', max_length=20, verbose_name='Источник заявки')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Организация')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пациента')),
                ('patient_age', models.IntegerField(blank=True, null=True, verbose_name='Возраст пациента')),
                ('preferred_contact_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Предпочтительное время для связи')),
                ('assigned_organization', models.CharField(blank=True, help_text='Сначала выберите тип организации, сохраните заявку, затем выберите организацию из списка', max_length=200, null=True, verbose_name='Назначенная организация')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('preferred_service', models.CharField(blank=True, max_length=200, null=True, verbose_name='Предпочтительная услуга')),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма комиссии')),
                ('commission_received_date', models.DateField(blank=True, null=True, verbose_name='Дата получения комиссии')),
                ('commission_document', models.FileField(blank=True, null=True, upload_to='commissions/', verbose_name='Документ комиссии')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Назначено')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип контента')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('organization_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.organizationtype', verbose_name='Тип организации')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_requests', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем')),
            ],
            options={
                'verbose_name': 'Анонимная заявка',
                'verbose_name_plural': 'Анонимные заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DependentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('waiting_commission', 'Ожидание комиссии'), ('commission_received', 'Комиссия получена'), ('treatment_started', 'Лечение начато'), ('treatment_completed', 'Лечение завершено'), ('cancelled', 'Отменена'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус')),
                ('addiction_type', models.CharField(choices=[('alcohol', 'Алкоголь'), ('drugs', 'Наркотики'), ('gambling', 'Игровая зависимость'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип зависимости')),
                ('contact_type', models.CharField(choices=[('anonymous', 'Анонимно'), ('pseudonym', 'Под псевдонимом'), ('real_name', 'Под реальным именем')], default='anonymous', max_length=20, verbose_name='Тип контакта')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('pseudonym', models.CharField(blank=True, max_length=100, null=True, verbose_name='Псевдоним')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('addiction_duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Длительность зависимости')),
                ('previous_treatment', models.TextField(blank=True, null=True, verbose_name='Предыдущее лечение')),
                ('current_condition', models.TextField(blank=True, null=True, verbose_name='Текущее состояние')),
                ('preferred_treatment', models.TextField(blank=True, null=True, verbose_name='Предпочтительный вид лечения')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактное лицо')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон контактного лица')),
                ('extra_notes', models.TextField(blank=True, null=True, verbose_name='Дополнительные заметки')),
                ('assigned_organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Назначенная организация')),
                ('organization_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.organizationtype', verbose_name='Тип организации')),
                ('responsible_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Заявка от зависимого',
                'verbose_name_plural': 'Заявки от зависимых',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DependentRequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.TextField(verbose_name='Текст')),
                ('is_important', models.BooleanField(default=False, verbose_name='Важное')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='requests.dependentrequest', verbose_name='Заявка от зависимого')),
            ],
            options={
                'verbose_name': 'Заметка к заявке от зависимого',
                'verbose_name_plural': 'Заметки к заявкам от зависимых',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DependentRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('waiting_commission', 'Ожидание комиссии'), ('commission_received', 'Комиссия получена'), ('treatment_started', 'Лечение начато'), ('treatment_completed', 'Лечение завершено'), ('cancelled', 'Отменена'), ('closed', 'Закрыта')], max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('waiting_commission', 'Ожидание комиссии'), ('commission_received', 'Комиссия получена'), ('treatment_started', 'Лечение начато'), ('treatment_completed', 'Лечение завершено'), ('cancelled', 'Отменена'), ('closed', 'Закрыта')], max_length=20, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests.dependentrequest', verbose_name='Заявка от зависимого')),
            ],
            options={
                'verbose_name': 'История статусов заявки от зависимого',
                'verbose_name_plural': 'История статусов заявок от зависимых',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('status_change', 'Изменение статуса'), ('commission', 'Работа с комиссией'), ('note', 'Добавление заметки'), ('assign', 'Назначение'), ('other', 'Другое')], max_length=20, verbose_name='Действие')),
                ('details', models.TextField(verbose_name='Детали')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='requests.anonymousrequest', verbose_name='Заявка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_actions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действий',
                'verbose_name_plural': 'Логи действий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.TextField(verbose_name='Текст')),
                ('is_important', models.BooleanField(default=False, verbose_name='Важное')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_notes', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='requests.anonymousrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Заметка к заявке',
                'verbose_name_plural': 'Заметки к заявкам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('waiting_commission', 'Ожидание комиссии'), ('commission_received', 'Комиссия получена'), ('treatment_started', 'Лечение начато'), ('treatment_completed', 'Лечение завершено'), ('cancelled', 'Отменена'), ('closed', 'Закрыта')], max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('waiting_commission', 'Ожидание комиссии'), ('commission_received', 'Комиссия получена'), ('treatment_started', 'Лечение начато'), ('treatment_completed', 'Лечение завершено'), ('cancelled', 'Отменена'), ('closed', 'Закрыта')], max_length=20, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests.anonymousrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'История статусов',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('request_type', models.CharField(choices=[('consultation', 'Консультация'), ('treatment', 'Лечение'), ('rehabilitation', 'Реабилитация'), ('partner', 'Партнерство'), ('other', 'Другое')], max_length=20, verbose_name='Тип заявки')),
                ('template_text', models.TextField(verbose_name='Шаблонный текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Шаблон заявки',
                'verbose_name_plural': 'Шаблоны заявок',
                'ordering': ['name'],
            },
        ),
    ]
