# Generated by Django 5.1.8 on 2025-07-16 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentrequest',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип контента'),
        ),
        migrations.AddField(
            model_name='dependentrequest',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта'),
        ),
    ]
