# Generated by Django 5.1.8 on 2025-07-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_dependentrequest_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependentrequest',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='dependentrequest',
            name='object_id',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
