# Generated by Django 5.1.8 on 2025-07-16 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_alter_rehabcenter_min_price'),
        ('requests', '0004_remove_dependentrequest_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousrequest',
            name='assigned_organization',
            field=models.CharField(blank=True, help_text='Выберите конкретную организацию', max_length=200, null=True, verbose_name='Назначенная организация'),
        ),
        migrations.AddField(
            model_name='anonymousrequest',
            name='organization_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.organizationtype', verbose_name='Тип организации'),
        ),
        migrations.AddField(
            model_name='dependentrequest',
            name='assigned_organization',
            field=models.CharField(blank=True, help_text='Выберите конкретную организацию', max_length=200, null=True, verbose_name='Назначенная организация'),
        ),
        migrations.AddField(
            model_name='dependentrequest',
            name='organization_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.organizationtype', verbose_name='Тип организации'),
        ),
    ]
