# Generated by Django 5.1.8 on 2025-07-16 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_anonymousrequest_assigned_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependentrequest',
            name='notes',
        ),
        migrations.AddField(
            model_name='dependentrequest',
            name='extra_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные заметки'),
        ),
        migrations.AlterField(
            model_name='anonymousrequest',
            name='assigned_organization',
            field=models.CharField(blank=True, help_text='Сначала выберите тип организации, сохраните заявку, затем выберите организацию из списка', max_length=200, null=True, verbose_name='Назначенная организация'),
        ),
        migrations.AlterField(
            model_name='dependentrequest',
            name='assigned_organization',
            field=models.CharField(blank=True, help_text='Сначала выберите тип организации, сохраните заявку, затем выберите организацию из списка', max_length=200, null=True, verbose_name='Назначенная организация'),
        ),
        migrations.CreateModel(
            name='DependentRequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.TextField(verbose_name='Текст')),
                ('is_important', models.BooleanField(default=False, verbose_name='Важное')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_request_notes', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='requests.dependentrequest', verbose_name='Заявка от зависимого')),
            ],
            options={
                'verbose_name': 'Заметка к заявке от зависимого',
                'verbose_name_plural': 'Заметки к заявкам от зависимых',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DependentRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('completed', 'Завершена')], max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('completed', 'Завершена')], max_length=20, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests.dependentrequest', verbose_name='Заявка от зависимого')),
            ],
            options={
                'verbose_name': 'История статусов заявки от зависимого',
                'verbose_name_plural': 'История статусов заявок от зависимых',
                'ordering': ['-changed_at'],
            },
        ),
    ]
