# Generated by Django 5.1.8 on 2025-07-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_remove_dependentrequest_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('waiting_commission', 'Ожидание комиссии'), ('commission_received', 'Комиссия получена'), ('treatment_started', 'Лечение начато'), ('treatment_completed', 'Лечение завершено'), ('cancelled', 'Отменена'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='dependentrequeststatushistory',
            name='new_status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('waiting_commission', 'Ожидание комиссии'), ('commission_received', 'Комиссия получена'), ('treatment_started', 'Лечение начато'), ('treatment_completed', 'Лечение завершено'), ('cancelled', 'Отменена'), ('closed', 'Закрыта')], max_length=20, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='dependentrequeststatushistory',
            name='old_status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('waiting_commission', 'Ожидание комиссии'), ('commission_received', 'Комиссия получена'), ('treatment_started', 'Лечение начато'), ('treatment_completed', 'Лечение завершено'), ('cancelled', 'Отменена'), ('closed', 'Закрыта')], max_length=20, verbose_name='Старый статус'),
        ),
    ]
