# Generated by Django 5.1.11 on 2025-08-02 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Иконка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_system', models.BooleanField(default=False, help_text='Системные теги отображаются с иконками в интерфейсе', verbose_name='Системный тег')),
            ],
            options={
                'verbose_name': 'Тег историй',
                'verbose_name_plural': 'Теги историй',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление')], max_length=10, verbose_name='Действие')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Измененное поле')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Новое значение')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Лог действий администратора',
                'verbose_name_plural': 'Логи действий администраторов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='recovery_stories.recoverycategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория историй',
                'verbose_name_plural': 'Категории историй',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID учреждения')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('excerpt', models.TextField(help_text='Краткое описание истории для отображения в списке', max_length=500, verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recovery_stories/', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Keywords')),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='recovery_stories/meta_images/', verbose_name='Meta Image (OG/Twitter)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('conclusion_text', models.TextField(blank=True, null=True, verbose_name='Текст заключения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='recovery_stories.recoverycategory', verbose_name='Категория')),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ['clinic', 'rehabcenter']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип учреждения')),
            ],
            options={
                'verbose_name': 'История выздоровления',
                'verbose_name_plural': 'Истории выздоровления',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryStoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to='recovery_stories/images/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recovery_stories.recoverystory', verbose_name='История')),
            ],
            options={
                'verbose_name': 'Изображение истории',
                'verbose_name_plural': 'Изображения историй',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryStoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_tags', to='recovery_stories.recoverystory', verbose_name='История')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_tags', to='recovery_stories.recoverytag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег истории',
                'verbose_name_plural': 'Теги историй',
                'unique_together': {('story', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='recoverystory',
            name='tags',
            field=models.ManyToManyField(through='recovery_stories.RecoveryStoryTag', to='recovery_stories.recoverytag', verbose_name='Теги'),
        ),
    ]
