# Generated by Django 5.1.8 on 2025-06-24 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('recovery_stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор'),
        ),
        migrations.AddField(
            model_name='recoverycategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='recovery_stories.recoverycategory', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='recoverystory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='recovery_stories.recoverycategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='recoverystory',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['clinic', 'rehabcenter']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип учреждения'),
        ),
        migrations.AddField(
            model_name='recoverystoryimage',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recovery_stories.recoverystory', verbose_name='История'),
        ),
        migrations.AddField(
            model_name='recoverystorytag',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_tags', to='recovery_stories.recoverystory', verbose_name='История'),
        ),
        migrations.AddField(
            model_name='recoverystorytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_tags', to='recovery_stories.recoverytag', verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='recoverystory',
            name='tags',
            field=models.ManyToManyField(through='recovery_stories.RecoveryStoryTag', to='recovery_stories.recoverytag', verbose_name='Теги'),
        ),
        migrations.AlterUniqueTogether(
            name='recoverystorytag',
            unique_together={('story', 'tag')},
        ),
    ]
