# Generated by Django 5.1.11 on 2025-07-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery_stories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverystory',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='recovery_stories/meta_images/', verbose_name='Meta Image (OG/Twitter)'),
        ),
        migrations.AddField(
            model_name='recoverystory',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Keywords'),
        ),
    ]
